"""Application versioning"""

# DO NOT MODIFY!!!
#
# This module has been generated by and is currently maintained
# from verpy. To find out how to change the versioning information
# please refer to `verpy --help` for usage

VERSION = 'VERSION_TO_WRITE'
